// The router factory shared by the client boot (src/App.tsx), the per-request
// SSR setup (src/setup.tsx), and the single-flight collector
// (src/server-config.ts), so all three routers are identical.
import type { QueryClient } from '@tanstack/solid-query';
import type { RouterHistory } from '@tanstack/solid-router';
import { createRouter } from '@tanstack/solid-router';

// Generated by @tanstack/router-plugin from the files under src/routes.
import { routeTree } from './routeTree.gen';

// Router context, received by every loader: carrying the QueryClient here is
// the idiomatic Router + Query pairing.
export interface RouterContext {
  queryClient: QueryClient;
}

export function createAppRouter(queryClient: QueryClient, history?: RouterHistory) {
  return createRouter({
    routeTree,
    history,
    context: { queryClient },
    // Hovering (or touching) a <Link> runs the target route's loader early.
    defaultPreload: 'intent',
    defaultPendingComponent: () => <main>Loading…</main>,
    // A semantic choice, not a hydration workaround: without the router's
    // global catch boundary, errors — including redirect() thrown during
    // SSR — bubble past the router to this app's own boundaries and stream
    // handler instead of stopping at the router's ErrorComponent.
    disableGlobalCatchBoundary: true,
  });
}

// Registers the router's types library-wide (typed `to`/`params` on <Link>).
declare module '@tanstack/solid-router' {
  interface Register {
    router: ReturnType<typeof createAppRouter>;
  }
}
