// The router factory, shared by every side that needs an instance: the
// client boot (src/App.tsx), the per-request SSR setup (src/setup.tsx), and
// the single-flight collector (src/server-config.ts). One factory keeps the
// three routers identical — same tree, same defaults, same context.
import type { QueryClient } from '@tanstack/solid-query';
import type { RouterHistory } from '@tanstack/solid-router';
import { createRouter } from '@tanstack/solid-router';

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from './routeTree.gen';

// Router context: what every route's loader receives. Carrying the
// QueryClient here is the idiomatic Router + Query pairing — loaders
// prefetch into it, components read from it.
export interface RouterContext {
  queryClient: QueryClient;
}

export function createAppRouter(queryClient: QueryClient, history?: RouterHistory) {
  return createRouter({
    routeTree,
    history,
    context: { queryClient },
    // Intent-based preloading: hovering (or touching) a <Link> runs the
    // target route's loader early, so its queries are warming before the
    // click lands.
    defaultPreload: 'intent',
    defaultPendingComponent: () => <main>Loading…</main>,
    // A semantic choice, not a hydration workaround (the adapter's boundary
    // structure is symmetric between server and client either way): without
    // the router's global catch boundary, errors — including redirect()
    // thrown during SSR — bubble past the router to this app's own
    // boundaries and stream handler instead of stopping at the router's
    // ErrorComponent.
    disableGlobalCatchBoundary: true,
  });
}

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module '@tanstack/solid-router' {
  interface Register {
    router: ReturnType<typeof createAppRouter>;
  }
}
