import { RouterProvider, createRouter } from '@tanstack/solid-router';
import './App.css';

// Generated by @tanstack/router-plugin from the files under src/routes.
import { routeTree } from './routeTree.gen';

const router = createRouter({
  routeTree,
  defaultPendingComponent: () => <main>Loading…</main>,
});

// Registers the router's types library-wide (typed `to`/`params` on <Link>).
declare module '@tanstack/solid-router' {
  interface Register {
    router: typeof router;
  }
}

export default function App() {
  return <RouterProvider router={router} />;
}
